# Generated by Django 4.2.7 on 2023-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_borrowedbook_balance_after_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
